PROCESS BEFORE OUTPUT.
  MODULE pbo_status_0200.

*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TC_RECEIVER'
  MODULE TC_RECEIVER_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_RECEIVER_CHANGE_COL_ATTR.
  LOOP AT   GT_RECEIVER
       INTO GS_RECEIVER
       WITH CONTROL TC_RECEIVER
       CURSOR TC_RECEIVER-CURRENT_LINE.
*&SPWIZARD:   MODULE TC_RECEIVER_CHANGE_FIELD_ATTR
  ENDLOOP.
  module tc_pbo_final.





PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TC_RECEIVER'
  LOOP AT GT_RECEIVER.
    CHAIN.
      FIELD GS_RECEIVER-AD_SMTPADR.
      FIELD GS_RECEIVER-COPY.
      FIELD GS_RECEIVER-BLIND_COPY.
      MODULE TC_RECEIVER_MODIFY ON CHAIN-REQUEST.
    endchain.
  ENDLOOP.
*&SPWIZARD: MODULE TC_RECEIVER_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TC_RECEIVER_CHANGE_COL_ATTR.


  MODULE user_command_0200.
