PROCESS BEFORE OUTPUT.
  MODULE pbo_status_0300.
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'TS_ATTACHMENTS'
  MODULE TS_ATTACHMENTS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TS_ATTACHMENTS_CHANGE_COL_ATTR.
  LOOP AT   GT_ATTACHMENTS
       INTO GS_ATTACHMENT
       WITH CONTROL TS_ATTACHMENTS
       CURSOR TS_ATTACHMENTS-CURRENT_LINE.
*&SPWIZARD:   MODULE TS_ATTACHMENTS_CHANGE_FIELD_ATTR
  ENDLOOP.

* MODULE STATUS_0300.
*
PROCESS AFTER INPUT.
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'TS_ATTACHMENTS'
  LOOP AT GT_ATTACHMENTS.
    CHAIN.
      FIELD GS_ATTACHMENT-SUBJECT.
    endchain.
    FIELD GS_ATTACHMENT-BOX
      MODULE TS_ATTACHMENTS_MARK ON REQUEST.
  ENDLOOP.
  MODULE TS_ATTACHMENTS_USER_COMMAND.
*&SPWIZARD: MODULE TS_ATTACHMENTS_CHANGE_TC_ATTR.
*&SPWIZARD: MODULE TS_ATTACHMENTS_CHANGE_COL_ATTR.

* MODULE USER_COMMAND_0300.
MODULE user_command_0300.
